enable: true
botToken: token
chats:
  - -number
admins:
  - telegramUsername
serverStartMessage: "服务器启动了！"
serverStopMessage: "服务器关闭了！"
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logPlayerDeath: true
logPlayerAsleep: false
logPlayerAdvancement: true
minecraftFormat: "[%username%] §r%message%"
telegramFormat: "<b>%username%</b>:\n%message%"
strings:
  online: "<b>在线</b>"
  nobodyOnline: "<b>没人在线</b>"
  joined: "<b>%username%</b> 进入服务器"
  left: "<b>%username%</b> 退出服务器"
  asleep: "<b>%username%</b> 睡觉了"
  advancement: "<b>%username%</b> %type% <b>[%advancement%]</b>\n%description%"
  whitelist:
    addSucceed: "成功将%username%添加到白名单！"
    removeSucceed: "成功将%username%从白名单移除！"
    failed: "未能找到玩家%username%。"
    usage: "用法\n/whitelist <add/remove> <name> 将玩家加入或移除白名单（仅限管理员）\n/whitelist list 显示白名单玩家\n/whitelist <on/off> 开启/关闭白名单"
    noPermission: "没有权限！"
commands:
  time: "time"
  online: "online"
  chat_id: "chat_id"
  whitelist: "whitelist"
  meow: "meow"
telegramAPI: "api.telegram.org"
debug: true