enable: true
botToken: token
chats:
  - -number
admins:
  - telegramUsername
serverStartMessage: "服务器启动了！"
serverStopMessage: "服务器关闭了！"
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logPlayerDeath: true
logPlayerAsleep: false
logPlayerAdvancement: true
minecraftFormat: "[%username%] §r%message%"
telegramFormat: "<b>%username%</b>:\n%message%"
messageTrim: 30
strings:
  online: "<b>在线</b>"
  nobodyOnline: "<b>没人在线</b>"
  joined: "<b>%username%</b> 进入服务器"
  left: "<b>%username%</b> 退出服务器"
  asleep: "<b>%username%</b> 睡觉了"
  advancement: "<b>%username%</b> %type% <b>[%advancement%]</b>\n%description%"
  noPermission: "你没有权限这样做！"
commands:
  time: "time"
  online: "online"
  chat_id: "chat_id"
  meow: "meow"
  command: "command"
telegramAPI: "api.telegram.org"
debug: true
proxy:
  enabled: false
  host: "localhost"
  port: 10809
