name: SpigotTGBridge
version: "0.19"
api-version: "1.18"
main: org.kraftwerk28.spigot_tg_bridge.Plugin
softdepend:
  - Vault
description: Telegram <-> Minecraft communication plugin for Spigot.
commands:
  tgbridge_reload:
    description: "Reload Spigot TG bridge plugin"
    usage: /<command>
